### PR TITLE
Replace RE2 with std::regex

### PR DESCRIPTION
**Pull request by jpihl**
Hi,

I posted issue #33, but since I didn't get any response I just went with the simplest approach and removed ``RE2``. I hope this is something you have interest in.

Not having ``RE2`` greatly simplifies porting this library to multiple platforms. 

The following work has been done in this PR:
* Replaced ``RE2`` with ``std::regex``
* Removed ``ZeroMQ`` cmake script (it seemed to not be used anywhere?)
* Fixed bug in ``server.cpp`` where parameters was passed in an incorrect order.
* Started work on Windows support:
     - Remove unused imports not available on windows.
     - Fix issues reported by MSVC (Still missing some, I will correct these in a different PR)

I hope you find this work useful.

### CODE REVIEW

**Comment by benjamg** [comment]
@Jeffail is there any reason not to merge this, we could have builds to support both but if it's just a minor performance issue that feels excessive. What was our reasoning in using re2 over std::regex in the first place?

**Comment by jpihl** [comment]
Exactly my thinking. I'm not very familiar with your code base yet - but my guess is that the strings checked by the regex are fairly short - so I doubt the potential performance hit from switching to ``std::regex`` will be noticeable.

**Comment by Jeffail** [comment]
Hey @jpihl, really sorry, this one slipped under my radar. Originally this was simply a performance pre-optimization thing. In practice performance has never been an issue whereas the build complexity has, so I'm happy to merge. Thanks for taking the time to put this together.

**Comment by jpihl** [comment]
No problem, my pleasure. Thanks for making such a nice library, and making it so enjoyable to contribute :+1:

**Pull request merged**
